
tasks:
  - init: yarn install && yarn run build
    command: yarn run watch

vscode:
  extensions:
    - gencay.vscode-chatgptconfig-gitpod-file)
    - gencay.vscode-chatgpt# and commit this file to your remote git repository to share the goodness with others.
tasks:
  - init: yarn install && yarn run build
    command: yarn run watch
